package com.github.napalm.interfaces;

import java.util.Set;

/**
 * Allows a plugin or app to contribute lines to the default Spring beans XML file that gets auto-generated by Napalm
 * 
 * @author jacekf
 * 
 */
public interface BeansConfigurationContributor {

	/**
	 * @param contributedLines The currently contributed lines from other apps/plugins
	 */
	public void contribute(Set<String> contributedLines);
}
